---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

  - name: nginx2
    image: nginx:1.14.2
    ports:
    - containerPort: 81

  - name: nginx3
    image: nginx:1.14.2
    ports:
    - containerPort: 82

---
apiVersion: v1
kind: Pod
metadata:
  name: mypod2
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
